# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 10:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0011_auto_20171019_1052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.TextField(default='', max_length=1000)),
                ('qiwi', models.TextField(default='', max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=100000)),
                ('viewPrice', models.FloatField(default=1)),
                ('budget', models.FloatField(default=0)),
                ('phrases', models.TextField(max_length=100000)),
                ('targetViewCnt', models.IntegerField(default=0)),
                ('curViewCnt', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('ageTarget', models.IntegerField(default=0)),
                ('placeTarget', models.TextField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.TextField(default='', max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('dt', models.DateTimeField(default=datetime.datetime(2017, 10, 19, 10, 52, 14, 930624))),
                ('comments', models.ManyToManyField(to='mainApp.Comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
