# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20171019_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 11, 9, 3, 788215)),
        ),
    ]
