# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20171019_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcamp',
            name='clickPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 16, 22, 9, 854081)),
        ),
        migrations.AddField(
            model_name='marketcamp',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 16, 22, 9, 854050)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 16, 22, 9, 852563)),
        ),
    ]
