# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 17:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20171019_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 17, 27, 30, 201423)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='image',
            field=models.ImageField(default='pictures/template.jpg', upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 17, 27, 30, 201394)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 17, 27, 30, 199905)),
        ),
    ]
