# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20171019_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 18, 35, 30, 513574)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='image',
            field=models.ImageField(default='/media/template.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 18, 35, 30, 513548)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 18, 35, 30, 512050)),
        ),
    ]
