# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-20 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20171020_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcamp',
            name='adminApproved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 12, 8, 128697)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 12, 8, 128664)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 12, 8, 127009)),
        ),
    ]
