# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-20 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_auto_20171020_1227'),
        ('customer', '0013_auto_20171020_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcamp',
            name='comments',
            field=models.ManyToManyField(to='mainApp.Comment'),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 27, 41, 293951)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 27, 41, 293923)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 27, 41, 292358)),
        ),
    ]
