# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-26 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20171023_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcamp',
            name='vkPostID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 13, 34, 51, 271860)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 13, 34, 51, 271831)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 13, 34, 51, 270224)),
        ),
    ]
