# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-30 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20171026_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 57, 44, 468129)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 57, 44, 468089)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 57, 44, 466259)),
        ),
    ]
