# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20171030_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcamp',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='mainApp.Comment'),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 7, 20, 23, 410198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='phrases',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='placeTarget',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 7, 20, 23, 410161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 7, 20, 23, 408232, tzinfo=utc)),
        ),
    ]
