# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20171108_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcamp',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 28, 38, 862518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='marketcamp',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 28, 38, 862489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='replenishtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 28, 38, 860925, tzinfo=utc)),
        ),
    ]
