# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('kiwi', models.TextField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=100000, null=True)),
                ('subText', models.TextField(blank=True, max_length=100000, null=True)),
                ('appendText', models.TextField(blank=True, max_length=100000, null=True)),
                ('caption', models.TextField(blank=True, max_length=100000, null=True)),
                ('pageName', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=100000)),
                ('viewPrice', models.FloatField(default=1)),
                ('budget', models.FloatField(default=0)),
                ('phrases', models.TextField(max_length=100000)),
                ('targetViewCnt', models.IntegerField(default=0)),
                ('curViewCnt', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('ageTarget', models.IntegerField(default=0)),
                ('placeTarget', models.TextField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.TextField(max_length=10000)),
                ('insta_link', models.TextField(max_length=10000)),
                ('fb_link', models.TextField(max_length=10000)),
                ('balance', models.IntegerField(default=0)),
                ('kiwi', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerMarketCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewCnt', models.IntegerField(default=0)),
                ('link', models.TextField(max_length=1000)),
                ('marketCamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.MarketCamp')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Worker')),
            ],
        ),
    ]
