# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.TextField(max_length=10000)),
                ('insta_link', models.TextField(max_length=10000)),
                ('fb_link', models.TextField(max_length=10000)),
                ('balance', models.IntegerField(default=0)),
                ('kiwi', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='second_name',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kiwi',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workermarketcamp',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Consumer'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
