# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20171013_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='companyName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='second_name',
        ),
    ]
