# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20171013_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='kiwi',
            new_name='qiwi',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='kiwi',
        ),
        migrations.AddField(
            model_name='consumer',
            name='qiwi',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='fb_link',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='insta_link',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='vk_link',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
