# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 12:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_auto_20171013_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='')),
                ('dt', models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 36, 48, 45399))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(to='mainApp.Comment')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(to='mainApp.Comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Customer')),
            ],
        ),
    ]
