# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_comment_consumertransaction_customertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='tc',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='tc',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 40, 10, 395789)),
        ),
    ]
