# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20171013_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 40, 57, 863457)),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
