# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20171013_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 50, 47, 759869)),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 50, 47, 761140)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 50, 47, 758984)),
        ),
    ]
