# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20171013_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 13, 30, 8, 221431)),
        ),
        migrations.AlterField(
            model_name='consumertransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 13, 30, 8, 222332)),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 13, 30, 8, 223832)),
        ),
    ]
