# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20171013_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.TextField(default='', max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('dt', models.DateTimeField(default=datetime.datetime(2017, 10, 19, 10, 32, 52, 858054))),
            ],
        ),
        migrations.RemoveField(
            model_name='customertransaction',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='customertransaction',
            name='customer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 10, 32, 52, 855882)),
        ),
        migrations.AlterField(
            model_name='consumertransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 10, 32, 52, 856712)),
        ),
        migrations.DeleteModel(
            name='CustomerTransaction',
        ),
        migrations.AddField(
            model_name='replenishtransaction',
            name='comments',
            field=models.ManyToManyField(to='mainApp.Comment'),
        ),
        migrations.AddField(
            model_name='replenishtransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Customer'),
        ),
    ]
