# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20171019_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consumertransaction',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='consumertransaction',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketcamp',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='replenishtransaction',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='replenishtransaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='workermarketcamp',
            name='marketCamp',
        ),
        migrations.RemoveField(
            model_name='workermarketcamp',
            name='worker',
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 10, 52, 14, 927202)),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='ConsumerTransaction',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MarketCamp',
        ),
        migrations.DeleteModel(
            name='ReplenishTransaction',
        ),
        migrations.DeleteModel(
            name='WorkerMarketCamp',
        ),
    ]
