# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-20 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20171019_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 11, 53, 24, 957589)),
        ),
    ]
