# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-26 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_auto_20171023_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 13, 34, 51, 266289)),
        ),
    ]
