# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_auto_20171102_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 15, 44, 37, 753265, tzinfo=utc)),
        ),
    ]
