# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 11:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0037_auto_20171107_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TehSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 11, 28, 7, 4799, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tehsupport',
            name='comments',
            field=models.ManyToManyField(to='mainApp.Comment'),
        ),
    ]
