# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_auto_20171108_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehsupport',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 11, 55, 7, 875426, tzinfo=utc)),
        ),
    ]
