# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_auto_20171108_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 38, 54, 83711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tehsupport',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 38, 54, 85163, tzinfo=utc)),
        ),
    ]
