# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-09 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_auto_20171108_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 15, 0, 5, 30934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tehsupport',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 15, 0, 5, 32236, tzinfo=utc)),
        ),
    ]
