# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-20 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0015_auto_20171020_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='autoParticipate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='autoVKRepost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='autoWithDraw',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 14, 30, 50, 878306)),
        ),
    ]
