# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0018_auto_20171021_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='vk_link',
            new_name='vk_token',
        ),
        migrations.AddField(
            model_name='consumer',
            name='vk_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 11, 14, 12, 355811)),
        ),
    ]
