# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-26 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0022_auto_20171026_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumermarketcamp',
            old_name='worker',
            new_name='consumer',
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 15, 47, 37, 494238)),
        ),
    ]
