# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-30 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0023_auto_20171026_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumermarketcamp',
            name='postId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 57, 44, 470461)),
        ),
    ]
