# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0024_auto_20171030_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 7, 20, 23, 413401, tzinfo=utc)),
        ),
    ]
