# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0028_auto_20171108_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 31, 40, 216002, tzinfo=utc)),
        ),
    ]
