# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0031_auto_20171108_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 16, 33, 11, 308569, tzinfo=utc)),
        ),
    ]
