# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-09 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0032_auto_20171108_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='frozenBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='fb_link',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='insta_link',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='qiwi',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='vk_token',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 15, 0, 5, 42791, tzinfo=utc)),
        ),
    ]
