# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_auto_20171108_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='consumer',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
