# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sworks', '0004_auto_20170317_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptcomment',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterField(
            model_name='attemptcomment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 8, 9, 2, 538921)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 8, 9, 2, 544048)),
        ),
    ]
