# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sworks', '0008_auto_20170417_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptcomment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 17, 40, 55, 696173)),
        ),
        migrations.AlterField(
            model_name='attemptcomment',
            name='text',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='mark',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 17, 40, 55, 696173)),
        ),
    ]
