# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sworks', '0014_auto_20170505_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptcomment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 11, 38, 58, 761451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infotext',
            name='appendText',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='infotext',
            name='subText',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='infotext',
            name='text',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 14, 38, 58, 761451)),
        ),
    ]
