# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sworks', '0015_auto_20170505_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotext',
            name='caption',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='infotext',
            name='pageName',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='attemptcomment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 11, 55, 20, 500693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 14, 55, 20, 501693)),
        ),
    ]
